root: true
ignorePatterns:
  - "projects/**/*"
overrides:
  - files:
      - "*.ts"
    parserOptions:
      project:
        - tsconfig.json
      createDefaultProgram: true
    extends:
      - plugin:@angular-eslint/recommended
      - plugin:@angular-eslint/template/process-inline-templates
      - plugin:prettier/recommended
    rules:
      "@angular-eslint/component-class-suffix":
        - error
        - suffixes:
            - Component
            - Widget
      prettier/prettier:
        - warn
        - parser: typescript
  - files:
      - "*.html"
    extends:
      - plugin:@angular-eslint/template/recommended
  - files:
      - "*.html"
    excludedFiles:
      - "*inline-template-*.component.html"
    extends:
      - plugin:prettier/recommended
    rules:
      prettier/prettier:
        - warn
        - parser: angular
